#!/bin/bash

echo "=== Acro Extension Screenshot Fix Verification ==="
echo ""
echo "This script helps verify the screenshot capture fix."
echo ""

# Check if Chrome is running
if pgrep -x "Google Chrome" > /dev/null; then
    echo "✓ Chrome is running"
else
    echo "✗ Chrome is not running"
    echo "  Please start Chrome and load the extension"
    exit 1
fi

echo ""
echo "Manual Verification Steps:"
echo ""
echo "1. Open Chrome and go to: chrome://extensions"
echo "   - Find 'Acro Demo Recorder'"
echo "   - Click the reload button (circular arrow icon)"
echo ""
echo "2. Open the test page:"
echo "   - Navigate to: file://$(pwd)/test-page.html"
echo "   - Or run: open test-page.html"
echo ""
echo "3. Open the extension background console:"
echo "   - Go to: chrome://extensions"
echo "   - Find 'Acro Demo Recorder'"
echo "   - Click 'Service Worker' link"
echo "   - Console will open"
echo ""
echo "4. Start recording:"
echo "   - Click the extension icon"
echo "   - Click 'Start Recording'"
echo "   - Wait for countdown"
echo ""
echo "5. Test screenshot capture:"
echo "   - Click a button on the test page"
echo "   - Watch the console for:"
echo "     [Background] Capturing screenshot for tab: XXX"
echo "     [Background] Screenshot captured successfully"
echo ""
echo "6. Expected behavior:"
echo "   ✓ No 'Failed to capture screenshot' errors"
echo "   ✓ Screenshots are captured successfully"
echo "   ✓ Steps are uploaded to backend"
echo ""
echo "7. If still failing, check:"
echo "   - Is the recording tab the active/visible tab?"
echo "   - Is the browser window focused?"
echo "   - Are you on a chrome:// or extension:// page?"
echo "   - Check browser console (F12) for permission errors"
echo ""
echo "For detailed troubleshooting, see:"
echo "  extension/SCREENSHOT_TROUBLESHOOTING.md"
echo ""
